name: rent_onway
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  # intl package
  intl: ^0.18.1 
  # Utility packages
  http: ^1.1.8 
  logger: ^2.0.1
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/
    - assets/logos/logolight.png
    - assets/logos/logodark.png
    - assets/images/onboarding/
    - assets/images/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
